name: flutter_weigh_serial
description: 提供电子秤数据获取能力，支持 Android、Windows 平台。

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  usb_serial: ^0.4.0
  serial_port_win32: ^0.7.0
  rxdart: ^0.27.7
  dartx: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.rex.flutter_weigh_serial
    iosBundleIdentifier: com.rex.flutterWeighSerial
